favicon: null
name: ShannonCoe
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.1425532
  brandStrength: 0.5191489
  lightness: 0.7957447
  brandColors:
    - '#FCFBF9'
    - '#202001'
    - '#4B4A02'
    - '#6E6E20'
    - '#CFD1CD'
  rhythmicContrast: 0.2617021
typography_spectrum: 0.7319149
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5127659
analytics:
  twitter: null
  google: null
  facebook: null
