favicon: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
typography_spectrum: 0.92182
color:
  saturation: 0.375
  brandStrength: 0.5191489
  lightness: 0.8922052283305675
  brandColors:
    - '#FCFBF9'
    - '#202001'
    - '#4B4A02'
    - '#6E6E20'
    - '#CFD1CD'
  rhythmicContrast: 0.75
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
layout_spectrum: 0.89072
name: ShannonCoe
