name: ShannonCoe
favicon: null
layout_spectrum: 0.89072
typography_spectrum: 0.92182
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#83913c'
    - '#9e243d'
    - '#ff78c0'
  brandStrength: 0.5625
  lightness: 0.8922052283305675
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
